[workspace]
members = [
    "contracts/bank-account",
    "contracts/deposit-note",
    "contracts/withdraw-request-note",
    "integration"
]
resolver = "2"
edition = "2021"

[workspace.dependencies]
miden = { version = "0.8" }

